version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "04:00"
    ignore:
      - dependency-name: actions/setup-java

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
      time: "04:00"

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
      time: "04:00"
