name: SonarQube Analysis
author: SonarSource SA / Alex Vincent
description: Performs code-quality/code-smells analysis.

inputs:
  github-token:
    description: GitHub token for PR information
    required: true
  sonar-token:
    description: SonarQube/SonarCloud authentication token
    required: true
  sonar-host-url:
    description: SonarQube server URL
    required: false
    default: https://sonarcloud.io
  build-configuration:
    description: .NET build configuration (Debug or Release)
    default: Release
    required: false

runs:
  using: composite
  steps:
    # See https://docs.sonarsource.com/sonarqube/latest/devops-platform-integration/github-integration/adding-sonarqube-analysis-to-your-workflow/
    - name: actions/setup-java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Cache SonarQube packages
      uses: actions/cache@v6
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache SonarQube scanner
      id: cache-sonar-scanner
      uses: actions/cache@v6
      with:
        path: .sonar/scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner

    - name: dotnet tool update dotnet-sonarscanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p .sonar/scanner
        dotnet tool update dotnet-sonarscanner --tool-path .sonar/scanner

    - name: Build and analyze
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
        BUILD_CONFIGURATION: ${{ inputs.build-configuration }}
      run: |
        if [ -n "$SONAR_TOKEN" ]; then
          .sonar/scanner/dotnet-sonarscanner begin \
            /k:"${{ github.actor }}_${{ github.event.repository.name }}" \
            /o:"${{ github.actor }}" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.host.url="$SONAR_HOST_URL"
          dotnet build -c "$BUILD_CONFIGURATION"
          .sonar/scanner/dotnet-sonarscanner end /d:sonar.token="$SONAR_TOKEN"
        else
          echo "::warning title=SONAR_TOKEN::sonar-token is not set, skipping analysis of the build."
        fi
